# Generated by Django 6.0.8 on 2026-10-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='full_name',
        ),
    ]
